### ISSUE TITLE
RQ_INTRO

### ISSUE THREAD

**Issue by JuYeolYang** [STRCapstone/StyleTransfer_Capstone#1]
![Main page](https://github.com/STRCapstone/StyleTransfer_Capstone/assets/94973258/a1e65f01-8e75-48df-a065-6c0668f45907)

#### 상세 요구사항
1. STR 홈페이지가 이미지 변환을 해주는 서비스라는 것을 설명한다.
    ”당신의 추억을 새로 덧칠해 보세요.
    STR은 Style Transfer for Recollection의 약자로, 사용자가 업로드한 사진의 화풍을
    변환하여 새로운 그림을 만들어냅니다.
    다양한 옵션을 통해 당신이 원하는 사진을 만들 수 있습니다.
    반 고흐의 별이 빛나는 밤, 그랑드자트섬의 일요일 오후, 피카소의 추상화를 비롯해
    완전히 새로운 세상에 섞여들어가 보세요.
    캔버스 위로 당신의 추억이 새로 그려집니다.”

2. 다양한 이미지에 다양한 화가의 스타일을 적용한 예시들을 보여준다.

3. 화풍 변경 방식에 따라 달라지는 예시를 보여준다.

4. 이미지를 변환하는 과정이 포함되어있어야 한다.

5. 개발자 정보를 표시한다.
    ”단국대학교 SW융합대학 소프트웨어학과
    실무중심산학협력프로젝트1(캡스톤디자인-SW)
    양주열 오세강 윤영은”

#### 테스트
- 글자의 크기, 위치등 디자인 적인 요소와 글의 맥락 등 확인

**Comment by pilsungk-oss** [comment]
SRS에서 작성한대로 이슈 description을 채워 넣기 바랍니다.

**Comment by youngeunyoon** [comment]
구현 완료
