### ISSUE TITLE
Refactor Code Structure

### ISSUE THREAD

**Issue by JuYeolYang** [STRCapstone/StyleTransfer_Capstone#64]
각자 맡은 코드 모바일 최적화 수행

**Comment by JuYeolYang** [comment]
예시
ops
- strdb.py
~~

**Comment by JuYeolYang** [comment]
### static/css
- login_style.css
- register_style.css
- result_style.css
- wait.css

### templates
- auth
- - login.html
- - register.html
- transfer
- - result.html

**Comment by segangoh** [comment]
### static/css
- transfer_style.css

### static/js
- transfer.js

### templates
- transfer
- - process_bar.html
- - transfer.html

**Comment by youngeunyoon** [comment]
templates/
- index.html
- banner.html
- community/
  - community.html
- member/
  - board_popup.html
  - mypage.html
  - new_board_popup.html
  - new_post_button.html

static/css/
- banner_style.css
- board_popup_style.css
- community_style.css
- index_style.css
- mypage_style.css
- new_board_popup_style.css
- new_post_button_style.css

**Comment by JuYeolYang** [comment]
모바일 최적화는 포기.
flask 동작에 집중
